### ISSUE TITLE
Attachment fields not supported

### ISSUE THREAD

**Issue by codeNgamer** [domdomegg/airtable-ts#12]
Amazing project first off. I just ran into an issue and it looks like attachment fields are not supported?

I see     // Unsupported field PDF: fld1HpbrZ347mSq6Z in the typings generated by airtable-ts-codegen

Any workarounds for working with these field types?

**Comment by domdomegg** [comment]
Thanks for raising the issue! Attachment fields are now supported as of airtable-ts v1.4.0, and airtable-ts-codegen v1.2.0.
