### ISSUE TITLE
Problem with all dates fields

### ISSUE THREAD

**Issue by Squix** [domdomegg/airtable-ts#2]
Hi again :)

I spotted another bug, no date field (createdTime, lastModifiedTime, and so on...) seems to work.
Here's my table :

```(javascript)
const tableA = {
      name:"Demandes",
      baseId
      tableId
      schema: {foo:string},
      mappings: {foo:"flxblabla"}
    } as Table<{id:string, foo:string}>
```
**foo** is a _lastModifiedTime_ property in airtable. I have this error when getting a record of this table : _Expected field tblabcd.flxblabla to be able to map to ts type string, but got airtable type lastModifiedTime which can't._

I looked up the code, and I don't understand why it's not working.
Dates properties seem to be referenced in typeUtils.d.ts to map with string type...

**Comment by domdomegg** [comment]
`date` and `dateTime` fields should work as normal.

I've just added support for `createdTime` and `lastModifiedTime` to the most recent release. I'll also look at how we can support more types out of the box: it'd be good to get more coverage + have it fall back to sensible conversion defaults.
