### ISSUE TITLE
Allow Nullable Currency/Number Values

### ISSUE THREAD

**Issue by austinm911** [domdomegg/airtable-ts#6]
Very early testing out this package. Thanks for putting it together. Noticed the error is thrown from the code below when number or currency values are undefined/null (not sure how airtable defines a missing value). 

With my use case, I have a lot of these number/currency fields and often they will have undefined values, so this is a pretty significant assumption to enforce non-nullable number values.

https://github.com/domdomegg/airtable-ts/blob/ac8baed4b3119dc8da1bdb24ab5752922212f46c/src/mapping/fieldMappers.ts#L237

**Comment by domdomegg** [comment]
In your `schema`, try setting the type of your number of currency field that is sometimes empty to `number | null` (rather than `number`. Does this fix it?

**Comment by adammakesthingsdev** [comment]
Going to +1 this, I think this is super important as well. Manually changing all fields of the autogenerated schema defeats the purpose of this project. While strong typing of databases is important, we have to accept that realistically databases themselves will likely not be perfect. At the least, I would hope a config option would be considered, I'd be happy to make a PR if you want.

**Comment by domdomegg** [comment]
> Manually changing all fields of the autogenerated schema defeats the purpose of this project [...] I would hope a config option would be considered, I'd be happy to make a PR if you want.

@adammakesthingsdev This makes sense! I'd be happy to accept a PR to [airtable-ts-codegen](https://github.com/domdomegg/airtable-ts-codegen) to add an option (can be enabled by default) to allow nullable values in columns!

**Comment by adammakesthingsdev** [comment]
Thanks for the response. I ended up making a fork with that change exactly, plus a few more (toyed with requiring type for single select, gave up on that one). I'll make a PR for that when I have time.
Another thing I'd like to see is better schema naming - for example, I have a table called "Addresses". Dealing with each "Addresse" is mildly annoying - maybe an option to ask what each should be called when the script is ran? No idea if it's possible to scrape that from the metadata api ("What should each record be called?").
Cheers!
Adam

**Comment by domdomegg** [comment]
> Another thing I'd like to see is better schema naming - for example, I have a table called "Addresses". Dealing with each "Addresse" is mildly annoying - maybe an option to ask what each should be called when the script is ran? No idea if it's possible to scrape that from the metadata api ("What should each record be called?").

In airtable-ts-codegen, index.ts:52 is probably where you want to look. We could make the logic for autoconverting things into the singular better (either adding some basic logic, or using a library like [pluralize](https://www.npmjs.com/package/pluralize)).

If that doesn't suit your usecase, we could add config here - although I'd prefer to avoid adding config options like this where possible as it does add complexity.
